version: "3"
services:
  db:
    image: "postgres"
    container_name: "loki_postgres"
    env_file: "backend.env"
    ports:
      - "54320:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  backend:
    image: "pilvi"
    container_name: "pilvi"
    env_file: "backend.env"
    ports:
      - "8001:8000"
    links:
      - "db"
