version: '3'
services:
  web:
    image: 106820074386.dkr.ecr.eu-central-1.amazonaws.com/cloudy-testing-repository
    ports:
      - "8000:8000"
    logging:
      driver: awslogs
      options:
        awslogs-group: cloudy-testing-loggroup
        awslogs-region: eu-central-1
        awslogs-stream-prefix: web
